name: Publish

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        version: [Gemfile, latest]
        include:
          - {version: Gemfile, gemfile: Gemfile}
          - {version: latest, gemfile: .ci/Gemfile}
    runs-on: ubuntu-18.04
    name: 'Build / ${{ matrix.version }}'
    env:
      BUNDLE_GEMFILE: '${{ matrix.gemfile }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
          bundler-cache: true
      - name: jekyll build
        run: bundle exec jekyll build --drafts

  publish:
    needs: [build]
    runs-on: ubuntu-18.04
    name: Publish
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
          bundler-cache: true
      - name: Build
        run: bundle exec jekyll build --baseurl /jekyll-theme
      - name: Publish
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: _site
          single-commit: true
